### ISSUE TITLE
Crash when i want to copy coords

### ISSUE THREAD

**Issue by Alayden** [5andr0/PogoLocationFeeder#184] opened 2016-08-03 19:03 UTC

**Comment by Roxazlp** [comment] 2016-08-03 19:21
Just copy coords or using pokesniper2?
If you want to use it with pokesniper2, you need to activate register url by clicking on the batch file in the pokesniper2 folder named "register_url". If you don't activate this option, it will crash the feeder everytime you click on the crosshair.

**Comment by tensei** [comment] 2016-08-03 20:25
crosshair doesn't show if the registry entry doesn't exist

**Comment by Ilses** [comment] 2016-08-04 06:20
Hi -- can you post your log file so we can work to determine the cause?

**Comment by Ilses** [comment] 2016-08-05 05:30
Closing as duplicate of #147

**Closed by Ilses** 2016-08-05 05:30 UTC
