### ISSUE TITLE
Sniping pidgey, ratatta, caterpie.

### ISSUE THREAD

**Issue by arslancharyev31** [5andr0/PogoLocationFeeder#249] opened 2016-08-08 15:08 UTC
How do I setup my Feeder config, so it snipes only common pokemons for evolving like pidgey, caterpie, rattata, etc.? Are there any Discord server channels for these pokemons?

**Comment by xrhaomx** [comment] 2016-08-08 15:10
Why would you want to snipe these? they are literally everywhere, if you only want these then just turn sniping off

**Comment by arslancharyev31** [comment] 2016-08-08 15:11
For XP farming

**Comment by cl3537git** [comment] 2016-08-08 15:38
Its easy to setup the config in your bot to only snipe for these specific pokemon. The problem is you would need a source reporting them which I don't know of.

I think a better way to tackle the problem is to search on google for the guy that had an underground route for farming where it was only low level pokemon and you don't do sniping. You need to find a GPXfile route that has enough pokestops and only spawn low level stuff.

I'd say too much trouble and just use a faster bot, by rumour only Haxton bot is supposed to be very fast but I haven't tried but some claim 350k/hour.

**Comment by Ilses** [comment] 2016-08-08 19:27
Currently this is a bot config, so I'm going to close this. We'll probably look into a way to populate the feed with tons of pidgey/caterpie/weedle in the future, though.

**Closed by Ilses** 2016-08-08 19:27 UTC
