### ISSUE TITLE
Sniping with pokesniper2 not working?

### ISSUE THREAD

**Issue by ivanders21** [5andr0/PogoLocationFeeder#246] opened 2016-08-08 13:30 UTC
Hello,

i already copy ALL the pogo location feeder Files into pokesniper2 folder, then when i click on pokemon in pogo feeder, it says logging in then automatically close
help please?
thanks

**Comment by P4R4DiSi4C** [comment] 2016-08-08 14:38
Hello,
Same here, instant close after this message:
[https://puu.sh/qtZUh/db608adfdc.png](url)

**Comment by ExcuseMi** [comment] 2016-08-08 14:40
Duplicate of #242

**Closed by ExcuseMi** 2016-08-08 14:40 UTC
