### ISSUE TITLE
Pokesnipers API down

### ISSUE THREAD

**Issue by Hikamii** [5andr0/PogoLocationFeeder#77] opened 2016-08-02 06:08 UTC
![387c0c0ee7d0a0eea033a3409093b976](https://cloud.githubusercontent.com/assets/20787868/17318672/05dda324-5856-11e6-911b-aa372377f502.png)

Does anyone know how to fix this issue?

**Comment by akatimka** [comment] 2016-08-02 06:11
same issue

**Comment by incizzle** [comment] 2016-08-02 06:13
same issue

**Comment by tq01m4m** [comment] 2016-08-02 06:37
same issue

**Comment by 750z** [comment] 2016-08-02 06:39
whats a possible fix?

**Comment by Naldra** [comment] 2016-08-02 06:40
it is fixed in the Master, you can download it and run when u have visualstudio or wait for new release

**Comment by Naldra** [comment] 2016-08-02 06:46
![fixed](https://cloud.githubusercontent.com/assets/20788358/17319395/9ab8492c-588d-11e6-8909-218185d6d63b.jpg)

**Comment by tq01m4m** [comment] 2016-08-02 06:57
Thx,it works now.

**Comment by mhui1125** [comment] 2016-08-02 07:07
what does "Master" means?

**Comment by djbie** [comment] 2016-08-02 07:24
@Naldra can you give me new release from master?

**Comment by PackuMan** [comment] 2016-08-02 07:26
@Naldra when you add new release for this bug? i don't have visual studio to run the source code.. :(

**Comment by Ilses** [comment] 2016-08-02 08:23
New release should be up pretty soon -- probably no more than a couple of hours.

**Comment by mLgz0rn** [comment] 2016-08-02 10:03
Why is it that it's crying about the api being down?
Is it just an issue in the current release?
Because the api is clearly not down :p

**Comment by DerekCL** [comment] 2016-08-02 10:35
same issue with version 0.1.1

**Comment by Sylencer90** [comment] 2016-08-02 10:59
Yep same issue with hotfix version :/

**Comment by robertosartori** [comment] 2016-08-02 11:37
I can confirm, it is fixed on master brach. Just wait for the update (or use visual studio).

**Comment by harsh1412** [comment] 2016-08-02 11:58
Pliss update... :(

**Comment by Sylencer90** [comment] 2016-08-02 12:19
Just uninstalled visual studio 2 days ago -.- fuck me.

**Comment by itsjustbilly** [comment] 2016-08-02 12:38
can someone compile this?

**Comment by qwe900** [comment] 2016-08-02 12:41
https://drive.google.com/open?id=0B_sn0IbirxIUbFJydDE5Mm9pTmc

**Comment by moredhel92** [comment] 2016-08-02 12:49
ty it works fine now

**Comment by Sylencer90** [comment] 2016-08-02 13:08
Works fine but my bot keeps scanning for pokemon at the locations in the config file from necrobot, and occasonally uses the data from pokefeeder.

  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinDelayBetweenSnipes": 45000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,

is that the correct config?

**Comment by Undertrey** [comment] 2016-08-02 13:13
Mine:
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,

Good for me.

**Comment by qwe900** [comment] 2016-08-02 13:15
just delete the lsit.


Am 02.08.2016 um 15:08 schrieb Sylencer90:

**Comment by itsjustbilly** [comment] 2016-08-02 13:19
thanks for the compile :)

**Comment by qwe900** [comment] 2016-08-02 13:19
was just rightlick build, np :D

**Comment by BuggeDKarma** [comment] 2016-08-02 15:00
https://github.com/dgateles/PogoLocationFeeder

**Comment by Ilses** [comment] 2016-08-02 19:37
This seems to be fixed in latest release, so I'm closing the issue.

**Closed by Ilses** 2016-08-02 19:37 UTC
