### ISSUE TITLE
option to disabled the pogo-feed.mmoex.com

### ISSUE THREAD

**Issue by iwfu** [5andr0/PogoLocationFeeder#190] opened 2016-08-03 20:21 UTC
#i'm looking for only 90+ IV, so i set up the good channel discord in the config file but , pogofeeder can't stop feed with unknow server with weak iv. i guess it's from pogo-feed.mmoex.com ?
anyway can you add an option to disabled that please

**Comment by theloser** [comment] 2016-08-03 20:53
See #83 -- filtering channels is comming!

**Comment by Ilses** [comment] 2016-08-03 21:16
pogo-feed.mmoex.com/messages is the dedicated Discord feed. See wiki for details.

I'll close as duplicate of #83 (thanks, @theloser !)

**Closed by Ilses** 2016-08-03 21:16 UTC
