### ISSUE TITLE
nothing showing up

### ISSUE THREAD

**Issue by derikZG** [5andr0/PogoLocationFeeder#189] opened 2016-08-03 19:57 UTC
[2016-08-03 15:31:41][DEBUG] My version: 0.1.3.0 (or a later master). Remote version: 0.1.3.0.
[2016-08-03 15:31:41][INFO] Great! You already have the newest version (v0.1.3, or later master)
[2016-08-03 15:31:41][INFO] Application starting...
[2016-08-03 15:31:41][INFO] Connecting to feeder service pogo-feed.mmoex.com
[2016-08-03 15:31:42][INFO] Connection established. Waiting for data...
[2016-08-03 15:31:43][DEBUG] Discord message received: 209283402245865472: loool
[2016-08-03 15:31:43][DEBUG] Can't get coords from line: loool
[2016-08-03 15:31:43][DEBUG] Discord message received: 209260366784495616: onix? ??
[2016-08-03 15:31:43][DEBUG] Can't get coords from line: onix? ??
[2016-08-03 15:31:45][DEBUG] Discord message received: 208946520874156033: Slowbro 48.89087, 2.383782
[2016-08-03 15:31:45][WARN] Exception:

System.MissingMethodException: 找不到方法:“!!0[] System.Array.Empty()”。
   在 PogoLocationFeeder.GUI.Common.Output.PrintPokemon(SniperInfo sniperInfo, String server, String channel)
   在 PogoLocationFeeder.Program.<feedToClients>d__11.MoveNext() 位置 D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:行号 137
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PogoLocationFeeder.Program.<relayMessageToClients>d__12.MoveNext() 位置 D:\games\PogoLocationFeeder\PogoLocationFeeder\Program.cs:行号 149

How can i fix this?

**Comment by Ilses** [comment] 2016-08-03 20:00
Closing as duplicate of #186 -- should be fixed in the next release.

**Closed by Ilses** 2016-08-03 20:00 UTC

**Comment by derikZG** [comment] 2016-08-03 20:03
alright thx!
